version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_news
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  server:
    build: ./server
    environment:
      DATABASE_URL: \${DATABASE_URL}
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      ADMIN_TOKEN: \${ADMIN_TOKEN}
      TZ: Asia/Dhaka
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://server:3000
    depends_on:
      - server
    ports:
      - '3001:3000'

volumes:
  db_data:
